# Generated by Django 3.0 on 2020-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categorie',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport Wear'), ('O', 'Outwear')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('D', 'Danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
