# Generated by Django 3.0 on 2020-03-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200325_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
