# Generated by Django 3.0 on 2020-03-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200331_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='coupon',
        ),
    ]
